name: Serhat
favicon: null
layout_spectrum: 0.7807386305648834
typography_spectrum: 0.5610656482167542
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#8f8f8f'
    - '#cacaca'
    - '#3f3f3f'
  brandStrength: 0.29191930242814124
  lightness: 0.3355649271979928
  saturation: 0.5
  rhythmicContrast: 0.46948368521407247
purpose: []
